global.env = {
  GATSBY_META_SITEURL: `$(GATSBY_META_SITEURL)`,
  GATSBY_META_IMAGE: `$(GATSBY_META_IMAGE)`,
  GATSBY_ELASTIC: `$(GATSBY_ELASTIC)`,
  GATSBY_ELASTIC_INDEX: `$(GATSBY_ELASTIC_INDEX)`,
  GATSBY_SITE_MAP: `$(GATSBY_SITE_MAP)`,
  GATSBY_APOLLO_CLIENT: `$(GATSBY_APOLLO_CLIENT)`,
  GATSBY_META_DOMAIN: `$(GATSBY_META_DOMAIN)`,
};
